name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-24.04  # Обновляем run image

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2  # Устанавливаем новую версию buildx

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Flask API Image
      uses: docker/compose-action@v2  # Используем новую версию compose action
      with:
        file: ./docker-compose.yml
        context: .
        push: true

    - name: Build and Push Frontend Image
      uses: docker/compose-action@v2  # Используем новую версию compose action
      with:
        file: ./docker-compose.yml
        context: .
        push: true
